name: objectbox_example
description: A new Flutter project.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.16.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  objectbox: ^1.4.1
  objectbox_sync_flutter_libs: ^1.4.1

dev_dependencies:
  build_runner: ^2.1.7
  flutter_lints: ^1.0.4
  objectbox_generator: ^1.4.1

flutter:
  uses-material-design: true
